ds: huggan/AFHQv2
output_dir: ../out/ot/${ds}

image_key: image
image_size: 128
image_convert: RGB

n_epoch: 200
batch_size: 32
save_interval: 50
sampling_interval: 10
gradient_clipping: 5

loss: ot
data_loader: afhq_cat

model:
  channels: 3
  dim: 64
  dim_mults: [1, 2, 4, 8]

optimizer:
  lr: 1e-4
